# Generated by Django 4.0.6 on 2022-11-05 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Is the product available for sale?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='projects.organization'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.PositiveIntegerField(default=1, help_text='Market Price(USD), eg. 100'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='plan_description',
            field=models.CharField(default=1, help_text='Duration, Quality eg. 1 Month, 720p, 5K Views', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of products available'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_price',
            field=models.PositiveIntegerField(default=1, help_text='Price you are selling at(USD), eg. 50'),
            preserve_default=False,
        ),
    ]
