# Generated by Django 4.0.6 on 2022-11-04 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_organization_remove_plot_block_remove_sector_project_and_more'),
        ('core', '0002_remove_user_identity_card_remove_user_postal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='projects.organization'),
        ),
    ]
