# Generated by Django 4.0.6 on 2022-11-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='is_verifies',
            new_name='is_verified',
        ),
    ]
