# Generated by Django 4.0.6 on 2022-11-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_remove_subscription_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='bot',
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(blank=True, default=1, help_text='Number of months i.e 1', null=True),
        ),
    ]
